ExternalProject_Add (
	game
	PREFIX .
	CMAKE_CACHE_ARGS ${DEFAULT_ARGS}

	TMP_DIR tmp
	STAMP_DIR stamp
	DOWNLOAD_DIR download
	SOURCE_DIR "${CMAKE_CURRENT_SOURCE_DIR}/game"
	BINARY_DIR game
	INSTALL_DIR game

	DEPENDS SFML
)
