ExternalProject_Add (
	SFML
	GIT_REPOSITORY https://github.com/SFML/SFML.git
	GIT_TAG ff011dc51dc47373b0d49b087f8ac9d3d2bc8b06
	CMAKE_CACHE_ARGS ${DEFAULT_ARGS}

	TMP_DIR tmp
	STAMP_DIR stamp
	DOWNLOAD_DIR download
	SOURCE_DIR src/SFML
	BINARY_DIR SFML
	INSTALL_DIR SFML

	EXCLUDE_FROM_ALL True
)
